var num;
document.write("<h1>Value after variable declaration is " + num + "</h1>");
num=5;
document.write("<h1>Initial Value " + num + "</h1>");
num++;
document.write("<h1>Value after increment: " + num + "</h1>");
num=num +7;
document.write("<h1>Value after addition " + num + "</h1>");
num--;
document.write("<h1>Value after decrement: " + num + "</h1>");
num= num%3;
document.write("<h1>Remainder is: " + num + "</h1>");